# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Backup name')),
                ('percents_completed', models.FloatField(default=0, verbose_name='Percents completed')),
                ('start_backup_datetime', models.DateTimeField(default=datetime.datetime(2016, 11, 14, 14, 16, 39, 750257, tzinfo=utc), verbose_name='Start backup datetime')),
                ('finish_backup_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Finish backup datetime')),
                ('status', models.IntegerField(choices=[(1, 'Rodando'), (2, 'Terminado com sucesso'), (3, 'Terminado com erro')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Backups',
                'verbose_name': 'Backup',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='Log')),
                ('log_datetime', models.DateTimeField(default=datetime.datetime(2016, 11, 14, 14, 16, 39, 750925, tzinfo=utc), verbose_name='Finish backup datetime')),
                ('status', models.IntegerField(choices=[(1, 'Rodando'), (2, 'Terminado com sucesso'), (3, 'Terminado com erro')], default=1, verbose_name='Status')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_log', to='core.Backup', verbose_name='backup')),
            ],
            options={
                'verbose_name_plural': 'Backups Log',
                'verbose_name': 'Backup Log',
            },
        ),
    ]
