# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Backup name')),
                ('percents_completed', models.IntegerField(default=0, verbose_name='Percents completed')),
                ('backup_datetime', models.DateTimeField(default=datetime.datetime(2016, 11, 7, 1, 3, 43, 696980, tzinfo=utc), verbose_name='Backup datetime')),
                ('status', models.IntegerField(choices=[(1, 'Rodando'), (2, 'Inativo')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Backups',
                'verbose_name': 'Backup',
            },
        ),
    ]
