# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 1, 3, 56, 732440, tzinfo=utc), verbose_name='Backup datetime'),
        ),
    ]
