# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('designed_by', models.CharField(max_length=50, verbose_name='Designed by')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
                ('date', models.DateField(default=datetime.datetime(2016, 11, 14, 14, 30, 11, 559529, tzinfo=utc), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'System Information',
                'verbose_name_plural': 'Systems Informations',
            },
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 14, 30, 11, 560032, tzinfo=utc), verbose_name='Start backup datetime'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 14, 30, 11, 560892, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
    ]
