# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161114_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='database_ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Database Ip'),
        ),
        migrations.AddField(
            model_name='backup',
            name='databases',
            field=models.TextField(blank=True, null=True, verbose_name='Databases'),
        ),
        migrations.AddField(
            model_name='backup',
            name='folders_passed',
            field=models.TextField(blank=True, null=True, verbose_name='Folders passed'),
        ),
        migrations.AddField(
            model_name='backup',
            name='storage_ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Storage Ip'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 18, 9, 10, 744167, tzinfo=utc), verbose_name='Start backup datetime'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.IntegerField(choices=[(1, 'Rodando'), (2, 'Terminado com sucesso'), (3, 'Alerta'), (4, 'Erro')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 18, 9, 10, 744867, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Rodando'), (2, 'Terminado com sucesso'), (3, 'Alerta'), (4, 'Erro')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 18, 9, 10, 743633, tzinfo=utc), verbose_name='Date'),
        ),
    ]
