# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161117_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='folders_passed',
        ),
        migrations.AddField(
            model_name='backup',
            name='path_folders_passe',
            field=models.TextField(blank=True, null=True, verbose_name='Path folders pass'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 18, 38, 7, 286557, tzinfo=utc), verbose_name='Start backup datetime'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 18, 38, 7, 287318, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 18, 38, 7, 285992, tzinfo=utc), verbose_name='Date'),
        ),
    ]
