# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161106_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 1, 6, 53, 931619, tzinfo=utc), verbose_name='Backup datetime'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='percents_completed',
            field=models.FloatField(default=0, verbose_name='Percents completed'),
        ),
    ]
