# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161106_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='Log')),
                ('success', models.BooleanField(default=False, verbose_name='Success ?')),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backups Log',
            },
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 12, 59, 51, 37927, tzinfo=utc), verbose_name='Backup datetime'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_log', to='core.Backup', verbose_name='backup'),
        ),
    ]
