# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161117_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='databases',
            new_name='databases_passed',
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 19, 34, 26, 397852, tzinfo=utc), verbose_name='Start backup datetime'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 19, 34, 26, 398498, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 19, 34, 26, 397293, tzinfo=utc), verbose_name='Date'),
        ),
    ]
