# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-17 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161117_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='storage_destiny_path',
            field=models.TextField(default='', verbose_name='storage_destiny_path'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 19, 36, 50, 133305, tzinfo=utc), verbose_name='Start backup datetime'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 17, 19, 36, 50, 134041, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 19, 36, 50, 132758, tzinfo=utc), verbose_name='Date'),
        ),
    ]
