# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161118_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='database_ip',
        ),
        migrations.AddField(
            model_name='backup',
            name='database_storage_ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ip do banco e das pastas'),
        ),
        migrations.AddField(
            model_name='backup',
            name='folders_passed',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Pastas passadas para o storage'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 14, 28, 44, 765937, tzinfo=utc), verbose_name='Hora de início do backup'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='storage_destiny_path',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Caminho no storage dos backups'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 14, 28, 44, 766623, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 18, 14, 28, 44, 765457, tzinfo=utc), verbose_name='Date'),
        ),
    ]
