# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161118_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='databases_to_pass',
            field=models.TextField(blank=True, null=True, verbose_name='Bancos a passar'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='start_backup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 12, 19, 20, 177157, tzinfo=utc), verbose_name='Hora de início do backup'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 12, 19, 20, 178509, tzinfo=utc), verbose_name='Finish backup datetime'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 21, 12, 19, 20, 176549, tzinfo=utc), verbose_name='Date'),
        ),
    ]
